baseURL = "https://<username>.pages.dev"  # nanti diubah otomatis oleh Cloudflare
languageCode = "en-us"
title = "Writeup CTF"
theme = "ananke"

# Enable Git submodule content
[module]
  [module.hugoVersion]
    extended = true
    min = "0.120.0"

# Optional: auto-generate summary dari konten
[summary]
  length = 30