site_name: Rubberdust Notes
site_url: https://dhicosatria.github.io/portfolio
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link
  palette:
    accent: indigo

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - CTF:
      - Overview: ctf/index.md
      - advent-of-cyber_cyberstudent_2025:
        - Overview: docs/ctf/advent-of-cyber_cyberstudent_2025.md
        - Day 3 – Syndicate Infrastructure: ctf/advent-of-cyber_cyberstudent_2025/day_3_Syndicate-Infrastructure.md
      - Forensics: ctf/forensics.md
      - Crypto: ctf/crypto.md
  - Labs Simulation:
      - Overview: labs_simulate/index.md
  - Projects:
      - Overview: project/index.md
  - Test: test.md
  - About: about.md

